db:
  active:
    ipaddress: 10.0.13.70 
  database: orcl.blr.velankani.com
  port: 1521
  username: consolidated##alarm
  password: eagger
 
 
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@${db.active.ipaddress}:${db.port}/${db.database}
    username: ${db.username}
    password: ${db.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
         dialect: org.hibernate.dialect.Oracle9Dialect

 

